### ISSUE TITLE
converter spinning but not downloading?

### ISSUE THREAD

**Issue by scopeys112** [mr-feek/global-poker-hand-history-converter-chrome-extension#1]
the converter appears to be loading or downloading (spinning etc.), unclear if hands are being downloaded/converted as i am unaware of download location etc.

**Comment by mr-feek** [comment]
Hey @scopeys112 , thanks for the info. I'm currently working on adding in status indicators to show you what step the converter is currently on.

Could you tell me what stakes/game type you've played in your last 50 hands? This will help me fix your issue.

RE the status indicators, I might have a new version of the plugin released tonight.

**Comment by scopeys112** [comment]
@mr-feek I also wanted to say thank you for creating this,

4nl 6max

**Comment by mr-feek** [comment]
@scopeys112 thanks, I'll try to see what could be messing up. The ~1k hands I have in 4nl are importing correctly.

Would you be able to show me a screenshot of the chrome console after you press the download button?

You can open the chrome javascript console by pressing `⌥-⌘-J` (option + command + J)

**Comment by scopeys112** [comment]
![untitled](https://user-images.githubusercontent.com/35480802/34976696-525d7a62-fa5d-11e7-9316-11f190de514b.jpg)
@mr-feek

**Comment by mr-feek** [comment]
@scopeys112 I just drafted a new release of the extension, chrome said it can take ~ 1 hour to become available.

I added an output area to log some details about the conversion process. Could you give it a look tomorrow and paste the output here please?

It will look like this
![image](https://user-images.githubusercontent.com/5747667/34978819-54b58d62-fa54-11e7-8ced-6bc294d6a75a.png)

**Comment by scopeys112** [comment]
![untitled](https://user-images.githubusercontent.com/35480802/34980619-ba1a0442-fa6a-11e7-9c58-af75da81dc97.jpg)

trying at various hand amounts

**Comment by mr-feek** [comment]
Interesting.. thanks! I'll try to have a fix out tonight

**Comment by scopeys112** [comment]
just realized i may have taken an improper screenshot, 
![untitled](https://user-images.githubusercontent.com/35480802/35028510-07cb86c8-fb1c-11e7-80dd-4d47fe975baf.jpg)


@mr-feek

**Comment by mr-feek** [comment]
What version of chrome are you using?

**Comment by scopeys112** [comment]
![untitled](https://user-images.githubusercontent.com/35480802/35035478-1f015410-fb37-11e7-9486-a23e0683a71d.jpg)
@mr-feek

**Comment by mr-feek** [comment]
@scopeys112 would you be able to update the package to `0.1.1` (i just released it a few mins ago) and see if there is any luck / more output in the log area? 

I've tried 2 different users and on windows/mac and can't seem to find a problem :/

**Comment by mr-feek** [comment]
PS you'll have to refresh your global poker page to use the new version of the plugin

**Comment by scopeys112** [comment]
Could it be windows 8.1?

**Comment by mr-feek** [comment]
no new log info in the chrome extension area since the new version??

**Comment by scopeys112** [comment]
@mr-feek 
![untitled](https://user-images.githubusercontent.com/35480802/35079488-7e68d7de-fbcd-11e7-8e1c-eedd2a535bfa.jpg)

**Comment by mr-feek** [comment]
New release made that might give a little more output..

If this doesn't work, i'll try a different approach of having you enter the date to download all hands that have occurred since then.

**Comment by scopeys112** [comment]
It works !!!!!!!

**Comment by mr-feek** [comment]
🙌 thanks for bearing with me @scopeys112 ! This is still in a really alpha stage, i appreciate the feedback.

**Comment by scopeys112** [comment]
@ around 4500 hands at the conversion stage it freezes, still awesome though!

**Comment by mr-feek** [comment]
@scopeys112 there must be a weird type of hand that I haven't played yet (something like 3 blinds posted, everyone folds) or something like that. If you figure out which hand it is and are able to post a link to the hand history, I'll be able to fix it for you.

Please open a new issue for that!
