### ISSUE TITLE
Nitrogen Poker Support

### ISSUE THREAD

**Issue by mcvicker** [mr-feek/global-poker-hand-history-converter-chrome-extension#10]
Have you thought about supporting the nitrogensports poker room with this? The software seems largely the same. https://nitrogensports.eu/poker/play

**Comment by mr-feek** [comment]
I don't play on nitrogen, so I don't have any intention on implementing this plugin to work for nitrogen.

However after taking a quick glance, it does look like the same software, so someone who knows what they are doing could fork this repository and make it work pretty easily I would assume.

**Comment by mcvicker** [comment]
Unfortunately I don't know what I'm doing.

Here's what I've got - I have the new piece of UI installed on the nitrogen site, so that's working (modified the manifest.json file). I changed the background.js file in the following ways:

var urls to match the local urls. (for example
playerApiBaseUrl : "https://public.globalpoker.com/player-api/rest", on global is 
playerApiBaseUrl : "//csplb1.cubeia.com/player-api/rest", on the Nitrogen site), so I updated the two spots where that appears.

The wheel icon loads up and I get "port initialized" and "beginning fetching hands" but the process just seems to go forever and never finishes.

How can I troubleshoot this further?

-d

**Comment by mr-feek** [comment]
@mcvicker I'd recommend looking at the network calls in chrome. From what I recall, you'll have to look at the one for the chrome extension itself. I believe that is done by clicking on `Inspect Views > background.html` in the extension settings

![image](https://user-images.githubusercontent.com/5747667/40579448-57e2a292-60f5-11e8-8724-0c02c6842dbd.png)

You'll want to see if the API calls are actually being made, and what the responses for them are.

**Comment by mcvicker** [comment]
Thanks, I did manage to get it working
