### ISSUE TITLE
Update in global poker

### ISSUE THREAD

**Issue by nachishankar** [mr-feek/global-poker-hand-history-converter-chrome-extension#11]
Hey Mr Feek, 
If you're the same group fpm5022 - there is a new update on global and the hand history converter doesn't work anymore. Is there any way you could fix it?

**Comment by billy49** [comment]
+1, you would be my hero

**Comment by mr-feek** [comment]
I don't play on global anymore, would someone else be willing to fix the markup / css?

The problem is probably here: https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/blob/master/src/js/gp_override.js#L35

**Comment by nachishankar** [comment]
I could try - but I have no idea how to code that well. It'll take me a while to figure it out. If you could walk me through the code once - I might be able to do it though

**Comment by chrisp200** [comment]
I am pretty solid at css, but I'm lost in js.  if someone can tell which class is breaking this, I should be able to easily fix it.

**Comment by chrisp200** [comment]
Someone can correct me if I'm wrong, but is the only issue that  historyDateContainer class isn't on the Global Poker HH page anymore?  Do we just need to replace $historyDateContainer.append(template); with 
$skin__cell q_c.append(template);

**Comment by nachishankar** [comment]
I have no idea :|. I don't know what any of it even means

**Comment by CMaximus** [comment]
Please fix

**Comment by mr-feek** [comment]
https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/pull/12

**Comment by mr-feek** [comment]
this should be fixed now
