### ISSUE TITLE
Was working this morning

### ISSUE THREAD

**Issue by CMaximus** [mr-feek/global-poker-hand-history-converter-chrome-extension#14]
Is anyone else having an issue with their updated chrome extension? Mine was working this morning, now it does not work. Here is my code that was working this morning. Can anyone confirm/verify please?

![image](https://user-images.githubusercontent.com/43683767/47545186-e0173700-d8b8-11e8-9642-b7a9a2ca9fc8.png)

**Comment by CMaximus** [comment]
Right clicked on the background of the site and clicked inspect. Maybe this will help someone?

![image](https://user-images.githubusercontent.com/43683767/47545738-d8a55d00-d8bb-11e8-878d-7a5ab84420a1.png)

**Comment by CMaximus** [comment]
So I'm the only one having a problem?

**Comment by CMaximus** [comment]
RIP

**Comment by CMaximus** [comment]
Pretty please someone fix

**Comment by mr-feek** [comment]
@CMaximus since no one else is having issues, I think you may need to delete the chrome extension and follow the installation steps in the readme to re-install it and apply the update.

**Comment by CMaximus** [comment]
Thank you for replying Feek. Were you able to verify yours was working?

**Comment by CMaximus** [comment]
I have tried following the instructions on the read me. Would you be able to spend a few minutes with me screen sharing and waking me through? I have sent you some money on beer pay already :) and I am happy to compensate you again.

**Comment by CMaximus** [comment]
OMG i got it to work :) much love

**Comment by mr-feek** [comment]
@CMaximus glad to hear it!
