### ISSUE TITLE
Update To Global

### ISSUE THREAD

**Issue by Tizull** [mr-feek/global-poker-hand-history-converter-chrome-extension#15]
There was an update to Global poker and the hand converter is busted again.

**Comment by mr-feek** [comment]
On it, thanks.

**Comment by 5starkarma** [comment]
See the updates. Totally removed extension and rebuilt but it is not showing up in HH section. I am assuming I did something wrong. Any thoughts?

**Comment by mr-feek** [comment]
this is fixed now!

**Comment by Noobafied** [comment]
Idk why you have the kindness in your heart to do this for us but I hope you get the best drugs and baddest bitches .
