### ISSUE TITLE
Winning hands aren't converted correctly.

### ISSUE THREAD

**Issue by aloft-coding** [mr-feek/global-poker-hand-history-converter-chrome-extension#4]
When using HM2, it only converts losing hands. All winning hands give an error. I believe the format is not correct for winning hands.

**Comment by mr-feek** [comment]
Hey @mojo6911 , I don't have HM2 to test this out so I might need some help.

Would you be able to give me one of the hand histories that is unable to import, as well as what the error is?

Ideally you can give me:

- A link to the public hand on global poker
- The converted hand history (i can get this myself from the public hand link if you have that)
- HM2's error message.

Thanks!

**Comment by aloft-coding** [comment]
Also getting errors in PT4. Lots of invalid pot size.

https://pastebin.com/gqCgbWQY

**Comment by mr-feek** [comment]
I can't do much without the hand histories so that I know the bug to fix.

I'm going to assume this is a duplicate report of https://github.com/mr-feek/global-poker-hand-history-converter/issues/2 and https://github.com/mr-feek/global-poker-hand-history-converter/issues/4

**Comment by mr-feek** [comment]
@mojo6911 I've just released a new version (0.2.2). It should be available within the hour. I've fixed a few bugs RE side pots and posted dead blinds.

I highly recommend you purge your existing imported hands, and re-import. 

lemme know if you still have any issues.
