### ISSUE TITLE
The hands are not uploading properly

### ISSUE THREAD

**Issue by wookie123** [mr-feek/global-poker-hand-history-converter-chrome-extension#6]
Hey,  I contacted you through 2+2.  The hand histories are all uploading and showing that I am losing every single hand that I play.  I can post a screenshot if you want me to.

**Comment by wookie123** [comment]
![global](https://user-images.githubusercontent.com/35849290/35456302-fdb8a024-02a2-11e8-80b8-2f926901572e.png)

**Comment by mr-feek** [comment]
ok, this is defintely a bug, but only with HM2. I'll try to figure out whats going on @wookie123

**Comment by mr-feek** [comment]
hey @wookie123 ,

I just got my hands on a PC / HM2. I fixed the main bug and released a new version of the chrome extension `(0.2.3)`. There is still a 1% error in imports in HM2 for my ~3k hands, but it's at least more usable now.

I'll revisit the remaining issue when I have some more time.
