### ISSUE TITLE
PLO hands are being uploaded and added as NLHE hands

### ISSUE THREAD

**Issue by wookie123** [mr-feek/global-poker-hand-history-converter-chrome-extension#7]
![omaha2](https://user-images.githubusercontent.com/35849290/35597179-30dbbb9e-05eb-11e8-995f-ed7ebc6b0179.png)

![omaha1](https://user-images.githubusercontent.com/35849290/35597181-354b3308-05eb-11e8-9e1f-9569fb9fb785.png)

**Comment by wookie123** [comment]
It looks like PLO hands are being uploaded along with the NLHE hands.  The database does not know the difference between the two.  Is there a way to purge all these PLO hands or to just not upload them?

**Comment by mr-feek** [comment]
hmmm I don't have any PLO hands. I guess I'll play a few to see if it's an easy fix. Otherwise I'll just stop PLO hands from being converted.

**Comment by mr-feek** [comment]
@wookie123 https://github.com/mr-feek/global-poker-hand-history-converter/issues/3 has been fixed. Version `0.3.0` of this extension has just been published and will be available to everyone within the hour. PLO should now be supported.
